name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        run: |
          echo "[default]" > ~/.aws/config
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "region=us-east-1" >> ~/.aws/config

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_ENDPOINT }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_DEV }} .

      - name: Push Docker image to ECR
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY_DEV }}:latest ${{ secrets.ECR_ENDPOINT }}/${{ secrets.ECR_REPOSITORY_DEV }}:latest
          docker push ${{ secrets.ECR_ENDPOINT }}/${{ secrets.ECR_REPOSITORY_DEV }}:latest
